# EXERCICI 1
Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [17]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

data = iris.data
target = iris.target

print("Primeres 10 files de 'data':")
print(data[:10])

print("\n Primeres 10 files de 'target':")
print(target[:10])

Primeres 10 files de 'data':
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

 Primeres 10 files de 'target':
[0 0 0 0 0 0 0 0 0 0]


# EXERCICI 2
Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [9]:
concatenated_array = np.concatenate((data, target.reshape(-1,1)),axis=1)
print("Primers 5 registres:")
print(concatenated_array[:5])

Primers 5 registres:
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


# EXERCICI 3
Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [10]:
for i, feature_name in enumerate(iris.feature_names):
    print(f"Índex {i}: {feature_name}")

Índex 0: sepal length (cm)
Índex 1: sepal width (cm)
Índex 2: petal length (cm)
Índex 3: petal width (cm)


In [11]:
sepal_length = data[:, 0]
petal_length = data[:, 2]

mediana_sepal_length = round (np.median(sepal_length), 2)
desviacion_sepal_length = round (np.std(sepal_length), 2)

mediana_petal_length = round (np.median(petal_length), 2)
desviacion_petal_length = round (np.std(petal_length), 2)

print("Sepal length (cm):")
print("Mediana:", mediana_sepal_length)
print("Desviació Estàndar:", desviacion_sepal_length)

print("\nPetal length (cm):")
print("Mediana:", mediana_petal_length)
print("Desviación Estàndar:", desviacion_petal_length)

Sepal length (cm):
Mediana: 5.8
Desviació Estàndar: 0.83

Petal length (cm):
Mediana: 4.35
Desviación Estàndar: 1.76


# EXERCICI 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [12]:
muestra_aleatoria = np.random.choice(concatenated_array.shape[0], size=20, replace=False)
muestra_aleatoria_data = concatenated_array[muestra_aleatoria, :]

print("Mostra aleatòria de 20 registres:")
print(muestra_aleatoria_data)

Mostra aleatòria de 20 registres:
[[6.  3.4 4.5 1.6 1. ]
 [6.8 3.  5.5 2.1 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [6.4 3.2 4.5 1.5 1. ]
 [5.  3.  1.6 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.8 1.9 0.4 0. ]
 [7.2 3.2 6.  1.8 2. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.7 2.5 5.  2.  2. ]
 [6.1 3.  4.6 1.4 1. ]
 [5.5 2.5 4.  1.3 1. ]
 [7.2 3.  5.8 1.6 2. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.8 3.2 5.9 2.3 2. ]
 [6.7 3.1 4.4 1.4 1. ]
 [6.8 2.8 4.8 1.4 1. ]]


# EXERCICI 5
Crea una matriu que mostri: 

• La mitjana de cada característica per espècie. 

• La desviació estàndard de cada característica per espècie.

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
setosa_data = concatenated_array[concatenated_array[:, -1] == 0, :-1]
versicolor_data = concatenated_array[concatenated_array[:, -1] == 1, :-1]
virginica_data = concatenated_array[concatenated_array[:, -1] == 2, :-1]

mediana_setosa = np.median(setosa_data, axis=0)
std_setosa = np.std(setosa_data, axis=0)

mediana_versicolor = np.median(versicolor_data, axis=0)
std_versicolor = np.std(versicolor_data, axis=0)

mediana_virginica = np.median(virginica_data, axis=0)
std_virginica = np.std(virginica_data, axis=0)

print("Mitjana Setosa:", mediana_setosa)
print("Desviació Estàndar Setosa:", std_setosa)

print("\nMitjana Versicolor:", mediana_versicolor)
print("Desviació Estàndar Versicolor:", std_versicolor)

print("\nMitjana Virginica:", mediana_virginica)
print("Desviació Estànda Virginica:", std_virginica)

Mitjana Setosa: [5.  3.4 1.5 0.2]
Desviació Estàndar Setosa: [0.34894699 0.37525458 0.17191859 0.10432641]

Mitjana Versicolor: [5.9  2.8  4.35 1.3 ]
Desviació Estàndar Versicolor: [0.51098337 0.31064449 0.46518813 0.19576517]

Mitjana Virginica: [6.5  3.   5.55 2.  ]
Desviació Estànda Virginica: [0.62948868 0.31925538 0.54634787 0.27188968]


# EXERCICI 6
• Calcula la quantitat de mostres per espècie.

• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [19]:
mapeo_especies = {0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'}

mediana_por_especie = np.zeros(3)

for especie in range(3):
    mediana_por_especie[especie] = np.median(concatenated_array[concatenated_array[:, -1] == especie, 0])

muestras_por_especie = np.bincount(concatenated_array[:, -1].astype(int))

especie_con_max_mediana = np.argmax(mediana_por_especie)

print("Quantitat de mostres per espècie:\n")
for especie, cantidad in enumerate(muestras_por_especie):
    nombre_especie = mapeo_especies.get(especie, f'Espècie {especie}')
    print(f"{nombre_especie}: {cantidad} mostres")

nombre_especie_max_mediana = mapeo_especies.get(especie_con_max_mediana)
print("\nEspècie amb el valor màxim mitjana en sepal length (cm):", nombre_especie_max_mediana)
print("Mitjana màxima en sepal length (cm):", mediana_por_especie[especie_con_max_mediana])

Quantitat de mostres per espècie:

Setosa: 50 mostres
Versicolor: 50 mostres
Virginica: 50 mostres

Espècie amb el valor màxim mitjana en sepal length (cm): Virginica
Mitjana màxima en sepal length (cm): 6.5


# EXERCICI 7
• Calcula la matriu de correlació entre les variables.

• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

• Troba la mostra amb els pètals més grans.

In [20]:
matriz_correlacion = np.corrcoef(concatenated_array, rowvar=False)

print("Matriu de correlació:\n")
print(matriz_correlacion)

Matriu de correlació:

[[ 1.         -0.11756978  0.87175378  0.81794113  0.78256123]
 [-0.11756978  1.         -0.4284401  -0.36612593 -0.42665756]
 [ 0.87175378 -0.4284401   1.          0.96286543  0.9490347 ]
 [ 0.81794113 -0.36612593  0.96286543  1.          0.95654733]
 [ 0.78256123 -0.42665756  0.9490347   0.95654733  1.        ]]


In [22]:
petal_length = np.median(concatenated_array[:, 0])

valors_majors_mitjana = concatenated_array[concatenated_array[:, 0] > petal_length]

print("Els valors mes grans que la mitjana de la longitud del pètal son:\n")
print(valors_majors_mitjana)

Els valors mes grans que la mitjana de la longitud del pètal son:

[[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [6.5 2.8 4.6 1.5 1. ]
 [6.3 3.3 4.7 1.6 1. ]
 [6.6 2.9 4.6 1.3 1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [6.2 2.2 4.5 1.5 1. ]
 [5.9 3.2 4.8 1.8 1. ]
 [6.1 2.8 4.  1.3 1. ]
 [6.3 2.5 4.9 1.5 1. ]
 [6.1 2.8 4.7 1.2 1. ]
 [6.4 2.9 4.3 1.3 1. ]
 [6.6 3.  4.4 1.4 1. ]
 [6.8 2.8 4.8 1.4 1. ]
 [6.7 3.  5.  1.7 1. ]
 [6.  2.9 4.5 1.5 1. ]
 [6.  2.7 5.1 1.6 1. ]
 [6.  3.4 4.5 1.6 1. ]
 [6.7 3.1 4.7 1.5 1. ]
 [6.3 2.3 4.4 1.3 1. ]
 [6.1 3.  4.6 1.4 1. ]
 [6.2 2.9 4.3 1.3 1. ]
 [6.3 3.3 6.  2.5 2. ]
 [7.1 3.  5.9 2.1 2. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.5 3.  5.8 2.2 2. ]
 [7.6 3.  6.6 2.1 2. ]
 [7.3 2.9 6.3 1.8 2. ]
 [6.7 2.5 5.8 1.8 2. ]
 [7.2 3.6 6.1 2.5 2. ]
 [6.5 3.2 5.1 2.  2. ]
 [6.4 2.7 5.3 1.9 2. ]
 [6.8 3.  5.5 2.1 2. ]
 [6.4 3.2 5.3 2.3 2. ]
 [6.5 3.  5.5 1.8 2. ]
 [7.7 3.8 6.7 2.2 2. ]
 [7.7 2.6 6.9

In [23]:
tamany_petal = concatenated_array[:, 2] + concatenated_array[:, 3]

max_tamany_petal = np.argmax(tamany_petal)

index_mostra_max_tamany_petal = max_tamany_petal
valors_mostra_max_tamany_petal = concatenated_array[max_tamany_petal, :]

print("Índex de la mostra amb el pètal mes gran:", index_mostra_max_tamany_petal)
print("\nEls valors de les variables per a la mostra que té el pètal més gran són:", valors_mostra_max_tamany_petal)

Índex de la mostra amb el pètal mes gran: 118

Els valors de les variables per a la mostra que té el pètal més gran són: [7.7 2.6 6.9 2.3 2. ]


# EXERCICI 8
Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [25]:
media_longitud_petal_por_especie = [np.mean(concatenated_array[concatenated_array[:, -1] == especie, 2]) for especie in range(3)]
media_longitud_sepalo_por_especie = [np.mean(concatenated_array[concatenated_array[:, -1] == especie, 0]) for especie in range(3)]

diferencia_medias_por_especie = np.abs(np.array(media_longitud_petal_por_especie) - np.array(media_longitud_sepalo_por_especie))

especie_max_diferencia = np.argmax(diferencia_medias_por_especie)

nombre_especie_max_diferencia = mapeo_especies.get(especie_max_diferencia)

print(f"Espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals: {nombre_especie_max_diferencia}")
print(f"Diferència de mitjanas: {diferencia_medias_por_especie[especie_max_diferencia]}")


Espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals: Setosa
Diferència de mitjanas: 3.544
